# Description:
#   BUILD file for //loaner/web_app/backend/static_content.

package(
    default_visibility = [
        "//loaner:__subpackages__",
    ],
)

# ==============================================================================
# Files
# ==============================================================================

filegroup(
    name = "maintenance",
    srcs = [
        "maintenance.html",
    ],
)
