# Description:
#   BUILD file for //loaner.

package_group(
    name = "internal",
    packages = [
        "//loaner/...",
    ],
)

package(
    default_visibility = [
        ":__subpackages__",
    ],
)
