# Description:
#   BUILD file for //loaner/deployments/lib/ui.

package(
    default_visibility = [
        "//loaner:__subpackages__",
    ],
)

#########
# Tests #
#########

test_suite(
    name = "all_tests",
    tests = [
        "//loaner/deployments/lib/ui/components:all_tests",
    ],
)
